### ISSUE TITLE
这个项目的开源协议是什么?

### ISSUE THREAD

**Issue by soDoEasy** [shuaidd/qywx#12]
你好, 坐着我想咨询一下这个项目是什么开源协议的

**Comment by shuaidd** [comment]
完全开放的，方便你我他


原始邮件
***@***.***
***@***.***
***@***.***
发送时间:2021年12月27日(周一) 11:22
主题:[shuaidd/qywx] 这个项目的开源协议是什么? (Issue #12)


你好, 坐着我想咨询一下这个项目是什么开源协议的
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shuaidd** [comment]
欢迎提供优化意见和改进意见


原始邮件
***@***.***
***@***.***; ***@***.***
***@***.***
发送时间:2021年12月27日(周一) 17:08
主题:回复：[shuaidd/qywx] 这个项目的开源协议是什么? (Issue #12)


完全开放的，方便你我他


原始邮件
***@***.***
***@***.***
***@***.***
发送时间:2021年12月27日(周一) 11:22
主题:[shuaidd/qywx] 这个项目的开源协议是什么? (Issue #12)


你好, 坐着我想咨询一下这个项目是什么开源协议的
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
