### ISSUE TITLE
boot 2.5.6 和 cloud 2020.0.4版本升级问题

### ISSUE THREAD

**Issue by soDoEasy** [shuaidd/qywx#14]
我的项目使用的boot 2.5.6 和 cloud 2020.0.4版本
我直接修改example工程里的版本号如下:
![image](https://user-images.githubusercontent.com/57608792/148913163-f77dfdda-e449-4642-b2e3-e312ebb409be.png)
报错如下
![image](https://user-images.githubusercontent.com/57608792/148913464-3cb77d6f-e568-47ad-ae6b-877e0639fe60.png)
我在提示报错链接里查看 提醒说  缺少access_token参数

**Comment by shuaidd** [comment]
针对高版本这个我需要升级一下，或者自己配置一下  拦截器
![image](https://user-images.githubusercontent.com/20659972/148930125-fef6916b-5652-4e98-a596-0588da228b46.png)

**Comment by shuaidd** [comment]
我在下一个版本 会升级一下

**Comment by soDoEasy** [comment]
你准备什么时候升级版本呢 , 如果在最近可以升级,我就等你的版本

**Comment by shuaidd** [comment]
明天发自我的手机-------- 原始邮件 --------发件人： soDoEasy ***@***.***>日期： 2022年1月11日周二 19:15收件人： shuaidd/qywx ***@***.***>抄送： ddshuai ***@***.***>, Comment ***@***.***>主    题： Re: [shuaidd/qywx] boot 2.5.6 和 cloud 2020.0.4版本升级问题 (Issue #14)

你准备什么时候升级版本呢 , 如果在最近可以升级,我就等你的版本

**Comment by soDoEasy** [comment]
谢谢
