### ISSUE TITLE
调用微信接口，每个入参都有一个app参数，不太理解它的作用是什么

### ISSUE THREAD

**Issue by a13561234591** [shuaidd/qywx#18]
![image](https://user-images.githubusercontent.com/56335586/160067111-7c2cb111-8804-4fbc-9bf4-25dda8380ad3.png)
文档里边接口请求是没有这个参数的，希望大佬给解答一下

**Comment by shuaidd** [comment]
这个是为了对应企业微信里自建应用的，是自建应用别名，看我的例子就知道了
