### ISSUE TITLE
项目还维护吗？

### ISSUE THREAD

**Issue by superleo-cn** [shuaidd/qywx#2]
我看目前不支持Markdown的消息，我能否发个PR，然后重新构建一下到maven公网仓库里面呢？

**Comment by shuaidd** [comment]
可以的发自我的华为手机-------- 原始邮件 --------发件人： superleo-cn <notifications@github.com>日期： 2020年12月29日周二 13:12收件人： shuaidd/qywx <qywx@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [shuaidd/qywx] 项目还维护吗？ (#2)

我看目前不支持Markdown的消息，我能否发个PR，然后重新构建一下到maven公网仓库里面呢？

**Comment by superleo-cn** [comment]
已经提交PR了，请Review后，在发布最新到maven中央仓库哈。

**Comment by shuaidd** [comment]
好的，晚上我看看

**Comment by superleo-cn** [comment]
问题已解决
