### ISSUE TITLE
企微通讯轮更新

### ISSUE THREAD

**Issue by LinkLiLiLi** [shuaidd/qywx#36]
你好,企业微信通讯录中关于人员信息的获取有更新,比如读取成员的接口已经不能使用了,这方面可以更新一下吗

**Comment by shuaidd** [comment]
我空了更新一下，好久没看企微changelog啦发自我的手机-------- 原始邮件 --------发件人： LiYang ***@***.***>日期： 2023年10月16日周一 11:30收件人： shuaidd/qywx ***@***.***>抄送： Subscribed ***@***.***>主    题： [shuaidd/qywx] 企微通讯轮更新 (Issue #36)
你好,企业微信通讯录中关于人员信息的获取有更新,比如读取成员的接口已经不能使用了,这方面可以更新一下吗

**Comment by LinkLiLiLi** [comment]
麻烦了 还有个小问题 在WeChatUser类里可以加上direct_leader这个字段吗

**Comment by shuaidd** [comment]
着急的话，你可以建pr，OK的话，我合过来发自我的手机-------- 原始邮件 --------发件人： LiYang ***@***.***>日期： 2023年10月19日周四 10:34收件人： shuaidd/qywx ***@***.***>抄送： ddshuai ***@***.***>, Comment ***@***.***>主    题： Re: [shuaidd/qywx] 企微通讯轮更新 (Issue #36)
麻烦了 还有个小问题 在WeChatUser类里可以加上direct_leader这个字段吗
