### ISSUE TITLE
目前拉取镜像出现下面错误

### ISSUE THREAD

**Issue by superleo-cn** [shuaidd/qywx#4]
[ERROR] Failed to execute goal on project : Could not resolve dependencies for project com.ttread:ttread-core:jar:1.0-SNAPSHOT: Could not find artifact com.github.shuaidd:qywx-spring-boot-autoconfigurator:jar:2.0.2 in alimaven (https://maven.aliyun.com/repository/central) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

我猜测是否只是starter打了2.0.2的标签，其他的没有跟着一起升呢？

**Comment by shuaidd** [comment]
中央仓库还没生效，我早晨上传的

**Comment by superleo-cn** [comment]
镜像已经更新了，问题已解决。
