### ISSUE TITLE
EventDataManager EventData 问题

### ISSUE THREAD

**Issue by cute2tiger** [shuaidd/qywx#9]
在这个方法里面当发送text 类型的消息时， commonEventData.getEvent() 是一直为空，不能执行后续代码。这个地方是否有点问题？

多谢

   public static BaseEventData getXmlData(String xml) {
        if (StringUtils.isEmpty(xml)) {
            return null;
        }

        CommonEventData commonEventData = XMLUtil.convertXmlStrToObject(CommonEventData.class, xml);
        if (StringUtils.isEmpty(commonEventData.getEvent())) {
            return null;
        }

**Comment by shuaidd** [comment]
你是怎么使用的 能否贴一下你的回调数据 我看看

**Comment by cute2tiger** [comment]
从腾讯企业微信回调回来的数据是这样的。
<xml>
<ToUserName><![CDATA[OOOOOOOOOOOOOO]]></ToUserName>
<FromUserName><![CDATA[XXXXX]]></FromUserName>
<CreateTime>1628080985</CreateTime>
<MsgType><![CDATA[text]]></MsgType><Content><![CDATA[hi abc]]></Content>
<MsgId>6992554588964372998</MsgId>
<AgentID>1000003</AgentID>
</xml>

![image](https://user-images.githubusercontent.com/5299709/128196118-89be9360-d20a-476c-9834-c7964ab33a79.png)

**Comment by shuaidd** [comment]
好的 感谢反馈，这个我扩展一下，顺便问一下 这个是企业微信后台哪里配置的回调 ，我可能漏掉了这一部分

**Comment by cute2tiger** [comment]
回调配置位于： 在企业微信后台的应用管理-->点击具体自己创建的应用-->接收消息-->配置API接收。
主要用于在用户在企业微信在聊天框发送消息后，我们自己开发的后台可以通过这个回调来接收消息，根据消息进行相应的回应。
https://open.work.weixin.qq.com/api/doc/90000/90135/90930

**Comment by shuaidd** [comment]
已在3.0.2版本修复
